- description: A JSON string containing any payload properties not present in the
    schema
  mode: NULLABLE
  name: additional_properties
  type: STRING
- fields:
  - mode: NULLABLE
    name: _19_24
    type: BOOL
  - mode: NULLABLE
    name: _25_34
    type: BOOL
  - mode: NULLABLE
    name: _35_44
    type: BOOL
  - mode: NULLABLE
    name: _45_54
    type: BOOL
  - mode: NULLABLE
    name: _55_64
    type: BOOL
  - mode: NULLABLE
    name: over_65
    type: BOOL
  mode: NULLABLE
  name: age
  type: RECORD
- description: The document ID specified in the URI when the client sent this message
  mode: NULLABLE
  name: document_id
  type: STRING
- fields:
  - mode: NULLABLE
    name: associates_degree
    type: BOOL
  - mode: NULLABLE
    name: bachelors_degree
    type: BOOL
  - mode: NULLABLE
    name: graduate_degree
    type: BOOL
  - mode: NULLABLE
    name: high_school_graduate_or_equivalent
    type: BOOL
  - mode: NULLABLE
    name: less_than_high_school
    type: BOOL
  - mode: NULLABLE
    name: some_college_but_no_degree_or_in_progress
    type: BOOL
  - mode: NULLABLE
    name: some_high_school
    type: BOOL
  mode: NULLABLE
  name: education
  type: RECORD
- fields:
  - mode: NULLABLE
    name: decline
    type: BOOL
  - mode: NULLABLE
    name: female
    type: BOOL
  - mode: NULLABLE
    name: male
    type: BOOL
  - mode: NULLABLE
    name: neither
    type: BOOL
  mode: NULLABLE
  name: gender
  type: RECORD
- fields:
  - mode: NULLABLE
    name: _0_24999
    type: BOOL
  - mode: NULLABLE
    name: _100000_149999
    type: BOOL
  - mode: NULLABLE
    name: _25000_49999
    type: BOOL
  - mode: NULLABLE
    name: _50000_74999
    type: BOOL
  - mode: NULLABLE
    name: _75000_99999
    type: BOOL
  - mode: NULLABLE
    name: ge_150000
    type: BOOL
  mode: NULLABLE
  name: income
  type: RECORD
- fields:
  - description: Results of a geographic lookup based on the client's IP address
    fields:
    - mode: NULLABLE
      name: city
      type: STRING
    - description: An ISO 3166-1 alpha-2 country code
      mode: NULLABLE
      name: country
      type: STRING
    - description: The specific geo database version used for this lookup
      mode: NULLABLE
      name: db_version
      type: STRING
    - description: First major country subdivision, typically a state, province, or
        county
      mode: NULLABLE
      name: subdivision1
      type: STRING
    - description: Second major country subdivision; not applicable for most countries
      mode: NULLABLE
      name: subdivision2
      type: STRING
    mode: NULLABLE
    name: geo
    type: RECORD
  - description: Headers included in the client's HTTP request
    fields:
    - description: Date HTTP header
      mode: NULLABLE
      name: date
      type: STRING
    - description: DNT (Do Not Track) HTTP header
      mode: NULLABLE
      name: dnt
      type: STRING
    - description: X-Debug-Id HTTP header
      mode: NULLABLE
      name: x_debug_id
      type: STRING
    - description: X-PingSender-Version HTTP header
      mode: NULLABLE
      name: x_pingsender_version
      type: STRING
    - description: X-Source-Tags HTTP header
      mode: NULLABLE
      name: x_source_tags
      type: STRING
    mode: NULLABLE
    name: header
    type: RECORD
  - description: Results of ISP lookup based on the client's IP address
    fields:
    - description: The specific geo ISP database version used for this lookup
      mode: NULLABLE
      name: db_version
      type: STRING
    - description: The name of the ISP associated with the client's IP address
      mode: NULLABLE
      name: name
      type: STRING
    - description: The name of a specific business entity associated with the client's
        IP address when available; otherwise the ISP name
      mode: NULLABLE
      name: organization
      type: STRING
    mode: NULLABLE
    name: isp
    type: RECORD
  - description: Parsed components of the client's user agent string
    fields:
    - mode: NULLABLE
      name: browser
      type: STRING
    - mode: NULLABLE
      name: os
      type: STRING
    - mode: NULLABLE
      name: version
      type: STRING
    mode: NULLABLE
    name: user_agent
    type: RECORD
  mode: NULLABLE
  name: metadata
  type: RECORD
- description: Set to "Other" if this message contained an unrecognized app name
  mode: NULLABLE
  name: normalized_app_name
  type: STRING
- description: Set to "Other" if this message contained an unrecognized channel name
  mode: NULLABLE
  name: normalized_channel
  type: STRING
- description: An ISO 3166-1 alpha-2 country code
  mode: NULLABLE
  name: normalized_country_code
  type: STRING
- description: Set to "Other" if this message contained an unrecognized OS name
  mode: NULLABLE
  name: normalized_os
  type: STRING
- mode: NULLABLE
  name: normalized_os_version
  type: STRING
- fields:
  - description: This field is deprecated in favour of hispanicLatinxSpanish
    mode: NULLABLE
    name: hispanic_latino_spanish
    type: BOOL
  - mode: NULLABLE
    name: hispanic_latinx_spanish
    type: BOOL
  - mode: NULLABLE
    name: other
    type: BOOL
  mode: NULLABLE
  name: origin
  type: RECORD
- description: Custom pioneer id, must not be Telemetry clientId
  mode: NULLABLE
  name: pioneer_id
  type: STRING
- fields:
  - mode: NULLABLE
    name: american_indian_or_alaska_native
    type: BOOL
  - mode: NULLABLE
    name: asian_indian
    type: BOOL
  - mode: NULLABLE
    name: black_or_african_american
    type: BOOL
  - mode: NULLABLE
    name: chamorro
    type: BOOL
  - mode: NULLABLE
    name: chinese
    type: BOOL
  - mode: NULLABLE
    name: filipino
    type: BOOL
  - mode: NULLABLE
    name: japanese
    type: BOOL
  - mode: NULLABLE
    name: korean
    type: BOOL
  - mode: NULLABLE
    name: native_hawaiian
    type: BOOL
  - mode: NULLABLE
    name: other_pacific_islander
    type: BOOL
  - mode: NULLABLE
    name: samoan
    type: BOOL
  - mode: NULLABLE
    name: some_other_race
    type: BOOL
  - mode: NULLABLE
    name: vietnamese
    type: BOOL
  - mode: NULLABLE
    name: white
    type: BOOL
  mode: NULLABLE
  name: races
  type: RECORD
- description: Bug 1677567 - Rally id reported by the core addon
  mode: NULLABLE
  name: rally_id
  type: STRING
- description: Hashed version of client_id (if present) useful for partitioning; ranges
    from 0 to 99
  mode: NULLABLE
  name: sample_id
  type: INT64
- description: Name of a particular study. Usually the addon_id.
  mode: NULLABLE
  name: study_name
  type: STRING
- description: Time when the ingestion edge server accepted this message
  mode: NULLABLE
  name: submission_timestamp
  type: TIMESTAMP
- mode: NULLABLE
  name: zip_code
  type: STRING
